### ISSUE TITLE
Text Macros

### ISSUE THREAD

**Issue by thiagomvas** [thiagomvas/Helium#3]
### Summary
Enable text macros in Helium where typing a trigger word followed by `TAB` expands to the specified macro. For example, typing `addr` and pressing `TAB` could expand to `123 Main St, Springfield`.

### Tasks

- [x] **Configuration**
  - [x] Use the existing config file to store macros under the `MACROS` section:
    ```
    MACROS
    key:value
    addr:123 Main St, Springfield
    sig:Best regards,\n[Your Name]
    ddx:\\frac{d}{dx}
    ```
  - [x] Parse `MACROS` as key-value pairs.

- [x] **Macro Detection & Replacement Logic**
  - [x] Bind `TAB` to trigger macro replacement.
  - [x] On `TAB` press:
    - [x] Capture the word under the cursor by scanning back to whitespace/delimiters.
    - [x] Check if it matches a key in `MACROS`.
  - [x] If matched, replace the word with the macro value.

- [x] **Fallback & Edge Cases**
  - [x] Default `TAB` behavior if no macro match.
  - [ ] Allow macros with placeholders to set the cursor, e.g., `Hello, [Name]`.

- [x] **User Customization**
  - [x] Allow users to edit the `MACROS` section in the config file for adding/removing macros.
  - [ ] Optional future enhancement: auto-reload updated `MACROS` without restarting.

### Acceptance Criteria
- Typing a macro trigger word + `TAB` replaces it with the macro text.
- Fallbacks to standard `TAB` behavior if no matching macro.

**Comment by thiagomvas** [comment]
Remaining tasks will come with future updates
